/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.repasoexamendi;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Color panelColor;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        panelColor = panelInfo.getBackground();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupContenedorRadio = new javax.swing.ButtonGroup();
        jPanelPanelColores = new javax.swing.JPanel();
        jRadioButtonAmarillo = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jPanelBotones = new javax.swing.JPanel();
        jButtonAmarillo = new javax.swing.JButton();
        jButtonAzul = new javax.swing.JButton();
        jButtonVerde = new javax.swing.JButton();
        jPanelNombre = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonResetar = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repaso examen");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        buttonGroupContenedorRadio.add(jRadioButtonAmarillo);
        jRadioButtonAmarillo.setText("Amarillo");
        jRadioButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmarilloActionPerformed(evt);
            }
        });

        buttonGroupContenedorRadio.add(jRadioButtonAzul);
        jRadioButtonAzul.setText("Azul");
        jRadioButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAzulActionPerformed(evt);
            }
        });

        buttonGroupContenedorRadio.add(jRadioButtonVerde);
        jRadioButtonVerde.setText("Verde");
        jRadioButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPanelColoresLayout = new javax.swing.GroupLayout(jPanelPanelColores);
        jPanelPanelColores.setLayout(jPanelPanelColoresLayout);
        jPanelPanelColoresLayout.setHorizontalGroup(
            jPanelPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelColoresLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonAmarillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonVerde)
                .addContainerGap())
        );
        jPanelPanelColoresLayout.setVerticalGroup(
            jPanelPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanelColoresLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAzul)
                    .addComponent(jRadioButtonVerde)
                    .addComponent(jRadioButtonAmarillo)))
        );

        getContentPane().add(jPanelPanelColores);

        jButtonAmarillo.setText("Amarillo");
        jButtonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmarilloActionPerformed(evt);
            }
        });

        jButtonAzul.setText("Azul");
        jButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzulActionPerformed(evt);
            }
        });

        jButtonVerde.setText("Verde");
        jButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonAmarillo)
                .addGap(5, 5, 5)
                .addComponent(jButtonAzul)
                .addGap(5, 5, 5)
                .addComponent(jButtonVerde))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAmarillo)
                    .addComponent(jButtonAzul)
                    .addComponent(jButtonVerde)))
        );

        getContentPane().add(jPanelBotones);

        Titulo.setText("Introduce un nombre: ");

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombreLayout = new javax.swing.GroupLayout(jPanelNombre);
        jPanelNombre.setLayout(jPanelNombreLayout);
        jPanelNombreLayout.setHorizontalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(0, 0, 0)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelNombreLayout.setVerticalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanelNombre);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar);

        jButtonResetar.setText("Resetear");
        jButtonResetar.setPreferredSize(new java.awt.Dimension(30, 20));
        jButtonResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResetar);

        panelInfo.setPreferredSize(new java.awt.Dimension(300, 100));

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(panelInfo);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jRadioButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmarilloActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.YELLOW);
        jLabelInfo.setText("Amarillo");
    }//GEN-LAST:event_jRadioButtonAmarilloActionPerformed

    private void jRadioButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdeActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.green);
        jLabelInfo.setText("Verde");
    }//GEN-LAST:event_jRadioButtonVerdeActionPerformed

    private void jRadioButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAzulActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.blue);
        jLabelInfo.setText("Azul");
    }//GEN-LAST:event_jRadioButtonAzulActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        if (texto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe introducir un campo");
        } else {
            PantallaInfo pantallaInfo = new PantallaInfo(this, false);
            pantallaInfo.setVisible(true);
            pantallaInfo.getInfo(texto.getText(),jLabelInfo.getText());
        }
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetarActionPerformed
        // TODO add your handling code here:
        buttonGroupContenedorRadio.clearSelection();
        jLabelInfo.setText("");
        texto.setText("");
        panelInfo.setBackground(panelColor);

    }//GEN-LAST:event_jButtonResetarActionPerformed

    private void jButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmarilloActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.YELLOW);
        jLabelInfo.setText("Amarillo");
    }//GEN-LAST:event_jButtonAmarilloActionPerformed

    private void jButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzulActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.BLUE);
        jLabelInfo.setText("Azul");
    }//GEN-LAST:event_jButtonAzulActionPerformed

    private void jButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerdeActionPerformed
        // TODO add your handling code here:
        panelInfo.setBackground(Color.GREEN);
        jLabelInfo.setText("Verde");
    }//GEN-LAST:event_jButtonVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroupContenedorRadio;
    private javax.swing.JButton jButtonAmarillo;
    private javax.swing.JButton jButtonAzul;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonResetar;
    private javax.swing.JButton jButtonVerde;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JPanel jPanelPanelColores;
    private javax.swing.JRadioButton jRadioButtonAmarillo;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonVerde;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
